/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package automatefcm;

import java.io.FileInputStream;
//import java.io.FileNotFoundException;

import com.google.auth.oauth2.GoogleCredentials;
import com.google.firebase.FirebaseApp;
import com.google.firebase.FirebaseOptions;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.messaging.FirebaseMessaging;
import com.google.firebase.messaging.Message;

public class Library {
    public boolean someLibraryMethod() {
    	try {
    		//System.out.println("before serviceAccount");
			//https://firebase.google.com/docs/admin/setup
    		FileInputStream serviceAccount =
				  new FileInputStream("./citizenandpolice-83361-firebase-adminsdk-witzk-c777f8ddc1.json");
			//System.out.println("before options");
			FirebaseOptions options = new FirebaseOptions.Builder()
		  			  .setCredentials(GoogleCredentials.fromStream(serviceAccount))
		  			  .setDatabaseUrl("https://citizenandpolice-83361.firebaseio.com") 
		  			  .build();
			//System.out.println("before initializeApp");
			FirebaseApp defaultApp = FirebaseApp.initializeApp(options);
			System.out.println("My app is " + defaultApp.getName());
			FirebaseAuth defaultAuth = FirebaseAuth.getInstance(defaultApp);
			FirebaseDatabase defaultDatabase = FirebaseDatabase.getInstance(defaultApp);

			//https://firebase.google.com/docs/cloud-messaging/send-message
			// This registration token comes from the client FCM SDKs.
			String registrationToken = "dnDKnrnkTKaT_UWkMOjeC9:APA91bFSHf4aXpztUkKuTqqluy-E0vptv1akYkGby2tAZocPnbFlZnwTbAPESfZSNPe24qQmxLWp3lDe6s5iXEIq0bbXm40i3raHOfjVJUy05l14h8_owRnKm7mCRHHMaCIOY_Ohvkz3";

			// See documentation on defining a message payload.
			Message message = Message.builder()
			    .putData("score", "850")
			    .putData("time", "2:45")
			    .putData("Server's message", "Thank God I made it")
			    .setToken(registrationToken)
			    .build();

			// Send a message to the device corresponding to the provided
			// registration token.
			String response = FirebaseMessaging.getInstance().send(message);
			// Response is a message ID string.
			System.out.println("Successfully sent message: " + response);
			//System.out.println("after initializeApp");
    	} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

  			
  		System.out.println("ending someLibraryMehod()");
    	return true;
    }
}
