/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package automatefcm;

import org.junit.Test;

import automatefcm.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        System.out.println("before assertTrue");
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//        System.out.println("ending testSomeLibraryMethod()");
    }
}
